// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqyeOIXqvvoUUXxzDKiVze_81M5Zd_780',
    appId: '1:379891080082:web:e3357490cec37c08b5bf4b',
    messagingSenderId: '379891080082',
    projectId: 'mynotes-example-apps',
    authDomain: 'mynotes-example-apps.firebaseapp.com',
    storageBucket: 'mynotes-example-apps.appspot.com',
    measurementId: 'G-9V3HSJM65D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKdrg8U3LmZbt99jscbZef5D9sshvSmQ',
    appId: '1:379891080082:android:a52212dfff4d2406b5bf4b',
    messagingSenderId: '379891080082',
    projectId: 'mynotes-example-apps',
    storageBucket: 'mynotes-example-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8o815yJQ2lgOiZ_3LpONvlbYOozveRYs',
    appId: '1:379891080082:ios:39521160f291921cb5bf4b',
    messagingSenderId: '379891080082',
    projectId: 'mynotes-example-apps',
    storageBucket: 'mynotes-example-apps.appspot.com',
    iosClientId: '379891080082-ntf4ec30042fpbl5sscpvm053im7ensh.apps.googleusercontent.com',
    iosBundleId: 'com.roy.mynotes',
  );
}
