name: first_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  url_launcher: 6.1.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
  assets:
    - assets/img1.jpg
    - assets/img2.jfif

